# Generated by Django 5.0.1 on 2026-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organization_multitenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='synceddocument',
            new_name='api_syncedd_entity__a0c9ab_idx',
            old_name='api_synceddo_entity__a8e2c4_idx',
        ),
        migrations.RenameIndex(
            model_name='synceddocument',
            new_name='api_syncedd_categor_5ba80d_idx',
            old_name='api_synceddo_categor_51f0b1_idx',
        ),
        migrations.RenameIndex(
            model_name='syncedentitystore',
            new_name='api_syncede_organiz_6369f6_idx',
            old_name='api_synced__org_ent_upd_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('PDG', 'PDG'), ('Comptable', 'Comptable'), ('Technique', 'Technique'), ('Gestionnaire', 'Gestionnaire'), ('Réceptionniste', 'Réceptionniste')], default='Gestionnaire', max_length=32),
        ),
    ]
