from django.urls import path

from api.views import (
    DatabaseInfoView,
    DatabaseResetView,
    DashboardSummaryView,
    ExecutiveOverviewView,
    ExecutiveIncidentsView,
    ExecutiveModuleDataView,
    ExecutiveNavigationView,
    ExecutiveNotificationsView,
    ExecutiveSyncLogView,
    ExecutiveTenantsView,
    ExpenseValidationActionView,
    HealthView,
    LoginView,
    SyncStatusView,
    SyncPullView,
    SyncPushView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("health", HealthView.as_view()),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/login", LoginView.as_view()),
    path("sync/push/", SyncPushView.as_view(), name="sync-push"),
    path("sync/push", SyncPushView.as_view()),
    path("sync/pull/", SyncPullView.as_view(), name="sync-pull"),
    path("sync/pull", SyncPullView.as_view()),
    path("sync/status/", SyncStatusView.as_view(), name="sync-status"),
    path("sync/status", SyncStatusView.as_view()),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("dashboard/summary", DashboardSummaryView.as_view()),
    path("executive/overview/", ExecutiveOverviewView.as_view(), name="executive-overview"),
    path("executive/overview", ExecutiveOverviewView.as_view()),
    path("executive/tenants/", ExecutiveTenantsView.as_view(), name="executive-tenants"),
    path("executive/tenants", ExecutiveTenantsView.as_view()),
    path("executive/incidents/", ExecutiveIncidentsView.as_view(), name="executive-incidents"),
    path("executive/incidents", ExecutiveIncidentsView.as_view()),
    path("executive/sync-logs/", ExecutiveSyncLogView.as_view(), name="executive-sync-logs"),
    path("executive/sync-logs", ExecutiveSyncLogView.as_view()),
    path("executive/navigation/", ExecutiveNavigationView.as_view(), name="executive-navigation"),
    path("executive/navigation", ExecutiveNavigationView.as_view()),
    path("executive/modules/<slug:slug>/", ExecutiveModuleDataView.as_view(), name="executive-module-data"),
    path("executive/modules/<slug:slug>", ExecutiveModuleDataView.as_view()),
    path("executive/notifications/", ExecutiveNotificationsView.as_view(), name="executive-notifications"),
    path("executive/notifications", ExecutiveNotificationsView.as_view()),
    path("executive/validations/expenses/<uuid:expense_id>/<str:action>/", ExpenseValidationActionView.as_view(), name="expense-validation-action"),
    path("executive/validations/expenses/<uuid:expense_id>/<str:action>", ExpenseValidationActionView.as_view()),
    path("executive/admin/database-info/", DatabaseInfoView.as_view(), name="database-info"),
    path("executive/admin/database-info", DatabaseInfoView.as_view()),
    path("executive/admin/reset-database/", DatabaseResetView.as_view(), name="database-reset"),
    path("executive/admin/reset-database", DatabaseResetView.as_view()),
]
